services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../src/{Command,EventListener,Service,Queue}'

    App\Controller\:
        resource: '../../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    # Autowiring the httpclient
    App\Service\DataDownloaderService:
        $httpClient: "@httplug.client.downloader"
        $tempFolder: '%kernel.project_dir%/var/temp'

    App\Service\DataService:
        $indexableContentTypes: "%indexable_content_types%"