httplug:
    plugins:
        logger: ~
    clients:
        downloader:
            factory: 'httplug.factory.guzzle6'
            plugins:
                - 'httplug.plugin.redirect'
                - 'httplug.plugin.retry'
