httplug:
    profiling:
        captured_body_length: 1000
    plugins:
        cache:
            cache_pool: 'local_cache'
            config:
                cache_lifetime: 360 # 10 minutes
                respect_response_cache_directives: ['max-age']
                methods: ['POST']
        logger: ~
    clients:
        downloader:
            factory: 'httplug.factory.guzzle6'
            plugins:
                - 'httplug.plugin.redirect'
                - 'httplug.plugin.retry'
        kregistry:
            factory: 'httplug.factory.guzzle6'
            plugins:
                - 'httplug.plugin.cache'
