services:
    _defaults:
        autowire: true
        autoconfigure: true
    # Autowiring the Registry client configurator
    OneOffTech\KLinkRegistryClient\HttpClientConfigurator:
      arguments:
        - "@httplug.client.kregistry"
      calls:
        -
          method: 'setEndpoint'
          arguments:
            - '%env(KLINK_REGISTRY_API_URL)%'

    OneOffTech\KLinkRegistryClient\ApiClient:
        factory: ['OneOffTech\KLinkRegistryClient\ApiClient', 'fromConfigurator']