framework:
    messenger:
        transports:
            default: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Queue\Message\DataProcessingMessage: default
            App\Queue\Message\DataDownloadMessage: default
