nelmio_solarium:
    endpoints:
        ksearch:
            host: "%env(SOLRCORE_HOST)%"
            core: "%env(SOLRCORE_NAME)%"
            # The following are the default parameters for Solarium client:
            # scheme: http
            # port: 8983
            # path: /solr
            timeout: 120
    clients:
        default:
            endpoints: [ksearch]
