services:
    queue_factory:
        class: Bernard\QueueFactory\PersistentFactory
        arguments:
            $connection: '@App\Queue\Driver\FlatFileDriver'
            $serializer: '@App\Queue\DataSerializer'

    Bernard\QueueFactory:
        alias: queue_factory

    App\Service\QueueService:
        $factory: '@queue_factory'

    App\Queue\Driver\FlatFileDriver:
        $rootDir: '%kernel.root_dir%'
