stages:
  - php-cs
  - test
  - build
  - release
  - deploy

cache:
  key: "ksearch"
  paths:
    - .composer-cache/

variables:
    CONTAINER_RELEASE_IMAGE_BASE: $CI_REGISTRY/images/ksearch

.need_composer: &need_composer
  before_script:
    - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache
    - php -v && composer --version
    - composer install --prefer-dist --no-interaction

##### Jobs
php-coding-styles:7.1:
  image: docker.klink.asia/main/docker-php:7.1
  <<: *need_composer
  stage: php-cs
  variables:
    APP_ENV: "dev"
    APP_DEBUG: "1"
    APP_SECRET: "774185ebf1c8d9ce0a8343eb2c4c3730"
  script:
    - mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.{ini,disabled}
    - scripts/run_phpcs.sh
    - bin/console > /dev/null
  tags:
    - docker

php-tests:7.1:
  image: docker.klink.asia/main/docker-php:7.1
  <<: *need_composer
  stage: test
  variables:
    APP_ENV: "dev"
    APP_DEBUG: "1"
    APP_SECRET: "774185ebf1c8d9ce0a8343eb2c4c3730"
  script:
    - scripts/run_phpunit.sh
  tags:
    - docker

## Normal branch release, we create local images for being used during tests
branch_release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME/v/} .
    - docker push $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME/v/}
  tags:
    - dind
  except:
    - tags

## Tagged releases
tagged_release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME/v/} .
    - docker push $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME/v/}
    - docker tag -f $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME/v/} "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  tags:
    - dind
  only:
    - tags
