stages:
  - php-cs
  - test
  - build
  - release
  - deploy

cache:
  key: "ksearch"
  paths:
    - .composer-cache/

variables:
    CONTAINER_RELEASE_IMAGE_BASE: $CI_REGISTRY/images/ksearch

.need_composer: &need_composer
  before_script:
    - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache
    - php -v && composer --version
    - composer install --prefer-dist --no-interaction

##### Jobs
php-coding-styles:7.1:
  image: docker.klink.asia/open/docker-php:7.1
  <<: *need_composer
  stage: php-cs
  variables:
    APP_ENV: "dev"
    APP_DEBUG: "1"
    APP_SECRET: "774185ebf1c8d9ce0a8343eb2c4c3730"
  script:
    - vendor/bin/php-cs-fixer fix --dry-run
  tags:
    - docker
