language: php

php:
  - 7.2
  - 7.3

branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

matrix:
  allow_failures:
    - php: 7.3

sudo: required

git:
  submodules: false

services:
  - docker

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - docker pull klinktech/k-search-engine:1.0.1-1
  - docker run --rm -d -p 127.0.0.1:8983:8983 --name engine klinktech/k-search-engine:1.0.1-1
  - docker ps -a

install:
  - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - phpenv config-rm xdebug.ini # disabling XDebug as currently we are not interested in code coverage report

script: 
  - scripts/run_phpcs.sh
  - bin/console > /dev/null
  - scripts/run_test_migrations.sh
  - scripts/run_test.sh

after_script:
  - docker stop engine && docker rm engine

notifications:
  email:
    on_success: never
