institution_api_get:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: InstitutionAPIBundle:Default:getInstitution
    requirements:
        id: "[a-zA-Z0-9]+"

institution_api_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: InstitutionAPIBundle:Default:deleteInstitution
    requirements:
        id: "[a-zA-Z0-9]+"

institution_api_post:
    path: /
    methods: [POST]
    defaults:
        _controller: InstitutionAPIBundle:Default:postInstitution
    requirements:

institution_api_getall:
    path: /
    methods: [GET]
    defaults:
        _controller: InstitutionAPIBundle:Default:getAllInstitutions
