#!/usr/bin/env bash
CONSOLE="bin/console"
CONFIG_FILE=".env"

# Dump the configuration to the .env file (this is mostly needed for the web app
# to easily configure the web server without downtime or Apache/Nginx specific configurations
echo "# Symfony configuration file, generated by Docker start.sh script" > ${CONFIG_FILE}
[[ ! -z "${APP_ENV+x}" ]] && echo "APP_ENV=${APP_ENV}" >> ${CONFIG_FILE}
[[ ! -z "${APP_DEBUG+x}" ]] && echo "APP_ENV=${APP_DEBUG}" >> ${CONFIG_FILE}
[[ ! -z "${SOLR_HOST+x}" ]] && echo "SOLR_HOST=${SOLR_HOST}" >> ${CONFIG_FILE}
[[ ! -z "${SOLR_CORE+x}" ]] && echo "SOLR_CORE=${SOLR_CORE}" >> ${CONFIG_FILE}
[[ ! -z "${KLINK_REGISTRY_ENABLED+x}" ]] && echo "KLINK_REGISTRY_ENABLED=${KLINK_REGISTRY_ENABLED}" >> ${CONFIG_FILE}
[[ ! -z "${KLINK_REGISTRY_API_URL+x}" ]] && echo "KLINK_REGISTRY_API_URL=${KLINK_REGISTRY_API_URL}" >> ${CONFIG_FILE}

rm -fr var/cache/*

${CONSOLE} cache:warmup

# Fix folder permissions
chown www-data:www-data --recursive ./var

# Start Supervisor daemon
supervisord
