---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

    ## Install Composer in the box
    - { role: composer }
    - { role: solr, solr_version: "5.5.4", solr_port: "8983", solr_core_name: "k-search", solr_core_conf: "/vagrant/solr/conf" }

    - { role: php-fpm, nginx_site_template: "symfony4-site.j2" }

    # K-Search specific tasks
    - { role: k-search }
