services:
    # Overriding services visibility for mocking
    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    # Define here the services that will be overridden to be public
    App\Service\DataService:
        $indexableContentTypes: "%indexable_content_types%"
        $retainDownloadedFiles: '%env(KLINK_RETAIN_DOWNLOADED_FILES)%'

    App\Security\Provider\KLinkRegistryUserProvider: ~

    # Autowire ApiSecretAuthenticator user provider
    App\Security\Authenticator\ApiSecretAuthenticator:
        $enabled: true

    Bernard\QueueFactory:
        class: Bernard\QueueFactory\InMemoryFactory
