# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

    # default values
    env(SOLR_HOST): '%env(SOLRCORE_HOST)%'
    env(SOLR_CORE): '%env(SOLRCORE_NAME)%'
    env(SOLRCORE_NAME): 'k-search'
    env(SOLRCORE_HOST): '127.0.0.1'
    env(KLINK_RETAIN_DOWNLOADED_CONTENTS): 0
    env(KLINK_REGISTRY_API_URL): ''
    env(ENQUEUE_DSN): 'file:'
    env(DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/data.db'

    indexable_content_types:
        - 'text/html'
        - 'application/msword'
        - 'application/vnd.ms-excel'
        - 'application/vnd.ms-powerpoint'
        - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        - 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
        - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        - 'application/pdf'
        - 'image/jpg'
        - 'image/jpeg'
        - 'image/gif'
        - 'image/png'
        - 'image/tiff'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appDebug: '%env(APP_DEBUG)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Controller,Queue}'

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    App\Service\DataDownloader:
        $httpClient: '@httplug.client.downloader'

    App\Service\DataFileNameGenerator:
        $downloadPath: '%kernel.project_dir%/var/data-downloads'

    App\Service\DataService:
        $indexableContentTypes: "%indexable_content_types%"
        $retainDataContents: '%env(KLINK_RETAIN_DOWNLOADED_CONTENTS)%'

    local_cache:
      class: 'Symfony\Component\Cache\Adapter\ApcuAdapter'

    # Autowiring the Registry client configurator
    OneOffTech\KLinkRegistryClient\HttpClientConfigurator:
      arguments:
        - "@httplug.client.kregistry"
      calls:
        -
          method: 'setEndpoint'
          arguments:
            - '%env(KLINK_REGISTRY_API_URL)%'

    OneOffTech\KLinkRegistryClient\ApiClient:
        lazy: true
        factory: ['OneOffTech\KLinkRegistryClient\ApiClient', 'fromConfigurator']

    # Autowire ApiSecretAuthenticator user provider
    App\Security\Authenticator\ApiSecretAuthenticator:
        $enabled: '%env(KLINK_REGISTRY_ENABLED)%'

    Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface:
        factory: ['Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser', 'getInstance']