services:
    security.access.documentdescriptor_voter:
        class: KCore\DocumentAPIBundle\Security\Authorization\Voter\DocumentDescriptorVoter
        public: false
        arguments: [@security.access.role_hierarchy_voter, %kcore.institution_id%]
        tags:
            - { name: security.voter }
