services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../src/*'
        exclude: '../../src/{Entity,Repository,Model,Search}'

    App\Controller\:
        resource: '../../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    # Autowiring the httpclient
    App\Command\DataProcessWorkerCommand:
        $httpClient: "@httplug.client.downloader"