name: Build Docker Image

on: 
  push:
    branches: 
      - "master"
      - "develop"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k-search
    - name: Login to Docker image
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
    - name: Push the Docker image
      run: |
        docker tag k-search klinktech/k-search:dev-develop
        docker push klinktech/k-search:dev-develop
