name: Build Docker Image

on: 
  push:
    branches: 
      - "master"
      - "develop"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k-search
    - name: Remove the Docker image
      run: docker rmi k-search
